### ISSUE TITLE
Make this project Go module aware

### ISSUE THREAD

**Issue by alwindoss** [s4y/reserve#1]

**Comment by s4y** [comment]
Done! (Fixed in 43e9c60cdc93ed629425d678cc30973deece583a.) Thanks for the reminder, I've been meaning to do that for a while. Let me know if anything looks off.

**Comment by alwindoss** [comment]
I think you should run `go mod tidy`
Currently your `go.mod` file contains `//indirect` dependencies which usually points to the fact that your module does not refer to them directly. But yours does.

Hope this helps

**Comment by s4y** [comment]
Oh, interesting. I did run it, but was browsing the project via a symlink in my `GOPATH` which was left over from the pre-module days, and that seems to have confused `go tidy`. I believe it's all better now — let me know if not.
